### ISSUE TITLE
Creating Menu In-Game

### ISSUE THREAD

**Issue by GershonR** [ustc-zzzz/VirtualChest#4]
I was wondering if it's possible to have a /virtualchest create [menu]

This will open a GUI, and you can put inside it blocks

**Comment by ustc-zzzz** [comment]
There isn't a GUI which could be used for configuration by putting blocks inside, and there won't be, either. The reason is simple. Items could have lores, enchantments or some other properties which are very difficult to configure by putting specifed items into the in game GUI, so I believe that the more expressive `.conf` configuration is the best choice.
