### ISSUE TITLE
Easy GUI stealing

### ISSUE THREAD

**Issue by Lorrainrm** [ustc-zzzz/VirtualChest#45]
Hello.
I'm able to easily pick an item from the GUI menu doing the following:

Shift + Left Click / Right Click
Then quickly pressing ESC (really fast)
The user gets the exacly item from the GUI.

Using SPONGE FORGE 1.12

**Comment by ustc-zzzz** [comment]
I've reproduced this bug and I found that in survival mode the item does not actually exist, and it will disappear as soon as the inventory is refreshed (sync to client from server, you can do this by pressing E), and I cannot steal the items successfully. I don't know if the appearance of this bug is the same as the one on your computer.

**Comment by Lorrainrm** [comment]
Ok. Will try to reproduce as survival and adv. Will let you know. Also i
just updated sponge. Let ser.  Thank you for replying.

Em 31 de jan de 2018 13:51, "Yanbing Zhao" <notifications@github.com>
escreveu:

**Comment by Lorrainrm** [comment]
Apparently i couldnt perform this in Adventure nor Survival, but could in Creative. That's not an issue. My concern was about the Other Gamemodes.

Thank you again!

**Comment by ustc-zzzz** [comment]
A player can fetch everything in Creative mode, so I also think that this is not a bug.
