### ISSUE TITLE
The specified chest GUI (<inventory>) is not found

### ISSUE THREAD

**Issue by Entitled** [ustc-zzzz/VirtualChest#49]
I'm not aware of where to ask for support with the plugin but I was led here so I created an account to do so
I've followed the wiki and the example files to structure the menu configuration with the slots and requirements although when I execute /vc o inventory player after executing /vc r in the server console I get prompted with the error The specified chest GUI (inventory) is not found all help is appreciated please and thank you
using spongeforge-1.12.2-2611-7.1.0-BETA-2970 and VirtualChest-1.0.0-alpha
only occurs to edited configurations the default example files open successfully

**Comment by ustc-zzzz** [comment]
There might be some syntax error or something else wrong in your configuration file. Please check if there are some error reported in you log file or console output when VirtualChest tries to load your configurations.

Besides, please provide a detailed stacktrace instead of a description which only has one sentence.
