### ISSUE TITLE
/help as alias for custom virtualchest

### ISSUE THREAD

**Issue by se7enek** [ustc-zzzz/VirtualChest#75]
Basically, aint an issue if there is fix for that, however...
How can i overwrite the default minecraft /help command with VirtualChest?
Just setting /help as alias, and executing /help, displays minecraft chat help, instead of virtual chest.

**Comment by se7enek** [comment]
Actually setting some sort of "priority" aka "overwrite" would be nice not only for /help but for others that may interfere too.

**Comment by ustc-zzzz** [comment]
It's possible by the system of sponge itself.

There should be an warning in your server log starting with `The command 'help' is not actually registered because it conflicts with the command ...`. Just follow the instructions and configure the part of command aliases in `config/sponge/global.conf`.
