### ISSUE TITLE
Support latest SpongeForge

### ISSUE THREAD

**Issue by Rubbertjuh** [ustc-zzzz/VirtualChest#8]
Latest SpongeForge breaks GUI, you can simply take the items out. 
I asked one of the Sponge devs about it: 
![image](https://cloud.githubusercontent.com/assets/15904543/24773679/5ba7ec5a-1b16-11e7-9f00-61688ac5765d.png)

meaning that this change will be permanent.
Thank you for your hard work on this project! Keep it up ;)

**Comment by ustc-zzzz** [comment]
Well, an emergency situation. I'm now looking up recent commits of SpongeForge and trying to fix this bug as quickly as possible.

**Comment by ustc-zzzz** [comment]
Ok, fixed. Try the latest version (v0.3.1) now. 
<hr>
The reason is that Sponge has inconsistent implementation of higher versions.
A slot has a parent. In the older version of sponge, inventories are grouped and the parent of the slot is only the red rectangle as shown below:
![screenshot from 2017-04-07 10-11-01](https://cloud.githubusercontent.com/assets/8004211/24786986/fd338b34-1b97-11e7-80e0-34789705588d.png)
while the parent of the slot is the whole inventory in the higher version. That causes the inconsistency.

**Comment by Rubbertjuh** [comment]
Thanks for the quick fix! Amazing job ;D
