### ISSUE TITLE
More Examples ?

### ISSUE THREAD

**Issue by Feutor** [ustc-zzzz/VirtualChest#92]
Hey this isnt exactly an issue but rather a question/request. I was wondering if theres like a repository for more examples so I dont have to do it all from scratch. I know that you learn the most by doing it yourself but a already working version of the general direction I wanna head (Pixelmon Server), gives me a way better start to achieving what I need and helps understand things way faster. I was also wondering if theres a Discord ? Cause maybe there are people who already shared a bunch of their virtual chests. If not, Id love to share mine once I am done, tbh.

**Comment by SourPath** [comment]
all available features are on the 2 examples, just pick the ones u need a build it from there, it's quite simple once u get the hang of it. As for discord I dont believe there is one

**Comment by Feutor** [comment]
In general, Discords always help a lot with communication and helping people with problemsolving but anyways, I finished the entire thing and I am quite happy with it, would have loved to realize that a simple =  was missing after the slot in order to add a slotitem if people dont meed required cash before I copy pasted my stuff across 30 menus but whatever, thats such a minor addition, I can add it with time, it's not like all menus will stop working if they dont have that feature and others do so I can take my time.

**Comment by ustc-zzzz** [comment]
> I was wondering if theres like a repository for more examples so I dont have to do it all from scratch.

As what was said from @iMystxc, almost all of the available features are shown in the 2 examples. There may be some menus created and shared by others while it's not my things.

> I was also wondering if theres a Discord?

Sorry, such a Discord Group does not exist, since Discord itself is blocked in China Mainland, the place which I come from. Of course, I can open Discord and receive messages by using some methods and you may find me in Sponge Discord of somewhere else, but I don't check it frequently. Please submit a GitHub issue if you find something that may not work as intended and I will see it in a relatively short time (I was busy recently so I didn't reply to you in time).

**Comment by Feutor** [comment]
Yeah its fine, I got it all
